POST http://localhost:3000/industrialist HTTP/1.1
content-type: application/json

{
    "name":"Chapak Farms",
    "password":"AVeryLongPassword",
    "address":"khett mei"
}
###
POST http://localhost:3000 HTTP/1.1
header name: header value

content

###
POST url HTTP/1.1
header name: header value

content